// ─────────────────────────────────────────────
// Generated by Scrapcraft Maker Lab
// Brain: "ECHO chip breadboard"  ·  Target: ESP32
// These are your tiles, as real firmware. Flash it to a robot.
// ─────────────────────────────────────────────

#define FORWARD 1
#define BACKWARD 0
#define RIGHT 1
#define LEFT 0
#define IN1 25
#define IN2 26
#define ENA 27
#define ENB 14

int echoBuf[64][2]; int echoLen=0; void echoRecord(int dpwm,int tpwm){ if(echoLen<64){ echoBuf[echoLen][0]=dpwm; echoBuf[echoLen][1]=tpwm; echoLen++; } } void echoReplay(){ for(int i=0;i<echoLen;i++){ analogWrite(ENA,echoBuf[i][0]); analogWrite(ENB,echoBuf[i][1]); delay(500); } analogWrite(ENA,0); analogWrite(ENB,0); }

void setup() {
}

void loop() {
  echoReplay();
  delay(1000);
}
