// ─────────────────────────────────────────────
// Generated by Scrapcraft Maker Lab
// Brain: "EMBER chip breadboard"  ·  Target: ESP32
// These are your tiles, as real firmware. Flash it to a robot.
// ─────────────────────────────────────────────

#define FORWARD 1
#define BACKWARD 0
#define RIGHT 1
#define LEFT 0
#include <Adafruit_INA219.h>

#define SDA 21
#define SCL 22
#define IN1 25
#define IN2 26
#define ENA 27
#define ENB 14
#define LED_R 14
#define LED_G 12
#define LED_B 33

Adafruit_INA219 ina219;
void emberGuard(int floorPct){ float v=ina219.getBusVoltage_V()/7.4; if(v*100<floorPct){ analogWrite(ENA,0); analogWrite(ENB,0); for(int i=0;i<6;i++){ digitalWrite(LED_R,HIGH); delay(150); digitalWrite(LED_R,LOW); delay(150); } } }

void setup() {
  ina219.begin();
}

void loop() {
  emberGuard(20);
  delay(1000);
}
