// ─────────────────────────────────────────────
// Generated by Scrapcraft Maker Lab
// Brain: "PILOT chip breadboard"  ·  Target: ESP32
// These are your tiles, as real firmware. Flash it to a robot.
// ─────────────────────────────────────────────

#define FORWARD 1
#define BACKWARD 0
#define RIGHT 1
#define LEFT 0
#define IR_L 34
#define IR_R 35
#define IN1 25
#define IN2 26
#define ENA 27
#define ENB 14

void pilotSeek(int kp,int base){ int err=analogRead(IR_R)-analogRead(IR_L); int corr=constrain(kp*err/4,-255,255); digitalWrite(IN1,HIGH); digitalWrite(IN2,LOW); analogWrite(ENA,base); analogWrite(ENB,constrain(base+corr,0,255)); }

void setup() {
}

void loop() {
  pilotSeek(60, 102);
  delay(1000);
}
