/**
 * Provider definitions used by both the in-game wizard and the Cloudflare worker.
 */
export const PROVIDERS = [
  {
    id: 'anthropic',
    name: 'Anthropic Claude',
    icon: '🤖',
    models: ['claude-sonnet-4-20250514', 'claude-haiku-3-5', 'claude-opus-4'],
    defaultModel: 'claude-sonnet-4-20250514',
    tier: 'premium',
    description: 'Best for Earl dialogue, Spark program generation',
    requiresKey: true,
    keyHint: 'sk-ant-...',
  },
  {
    id: 'openai',
    name: 'OpenAI',
    icon: '⚡',
    models: ['gpt-4o', 'gpt-4o-mini'],
    defaultModel: 'gpt-4o-mini',
    tier: 'premium',
    description: 'Fast generation, good for Spark robot programs',
    requiresKey: true,
    keyHint: 'sk-proj-...',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    icon: '🧠',
    models: ['deepseek-chat'],
    defaultModel: 'deepseek-chat',
    tier: 'budget',
    description: 'Open source reasoning model — great value',
    requiresKey: true,
    keyHint: 'sk-...',
  },
  {
    id: 'z.ai',
    name: 'Z.AI',
    icon: '⚡',
    models: ['z-ai-chat'],
    defaultModel: 'z-ai-chat',
    tier: 'budget',
    description: 'Fast inference provider',
    requiresKey: true,
    keyHint: 'Enter your Z.AI API key',
  },
  {
    id: 'deepinfra',
    name: 'DeepInfra',
    icon: '☁️',
    models: ['mistralai/Mixtral-8x22B', 'meta-llama/Llama-3.3-70B'],
    defaultModel: 'mistralai/Mixtral-8x22B',
    tier: 'budget',
    description: 'Serverless GPU — open models',
    requiresKey: true,
    keyHint: 'Enter your DeepInfra key',
  },
  {
    id: 'workers_ai',
    name: 'Workers AI (Cloudflare)',
    icon: '🌤️',
    models: ['@cf/meta/llama-3.1-8b-instruct', '@cf/mistral/mistral-7b'],
    defaultModel: '@cf/meta/llama-3.1-8b-instruct',
    tier: 'free',
    description: 'Free — runs on Cloudflare GPU. No key needed.',
    requiresKey: false,
    keyHint: null,
    requiresCfWorker: true,
  },
  {
    id: 'offline',
    name: 'Offline Mode',
    icon: '🔌',
    models: [],
    defaultModel: null,
    tier: 'free',
    description: 'No AI features. Earl uses preset dialogue. Spark uses offline fallback.',
    requiresKey: false,
    keyHint: null,
  },
];
