/**
 * ───────────────────────────────────────────────────────────────────────────
 *  FIRMWARE GEN  —  tile tree  →  real Arduino C++ / MicroPython
 * ───────────────────────────────────────────────────────────────────────────
 *
 *  Two jobs, same code path:
 *    • LAYER-3 VIEW   show an advanced student the real firmware behind their
 *                     tiles, side-by-side, in-game.
 *    • EXPORT BRIDGE  emit a flashable sketch (Arduino) or .py (MicroPython)
 *                     they can drop into Wokwi or onto a $6 ESP32.
 *
 *  This is what makes Scrapcraft a maker pipeline rather than a toy: the tiles a
 *  10-year-old dragged around become literal, correct embedded code. We walk the
 *  SAME tile tree the VM runs, so the simulation and the exported firmware are
 *  guaranteed to describe the same behaviour.
 *
 *  Helper functions (drive/turn/readBrightness/...) are emitted only for the
 *  primitives the program actually uses, keyed off primitives.js metadata.
 * ───────────────────────────────────────────────────────────────────────────
 */

import { getActuator, getSensor, BRAINS } from './primitives.js';
import { expandMacro } from './TileCompiler.js';

// Per-language helper bodies, emitted only when the matching primitive is used.
const ARDUINO_HELPERS = {
  drive: `void drive(int dir, int pwm){ digitalWrite(IN1, dir==FORWARD); digitalWrite(IN2, dir!=FORWARD); analogWrite(ENA, pwm); }`,
  turn:  `void turn(int dir, int pwm){ /* spin in place via differential drive */ analogWrite(ENA, pwm); analogWrite(ENB, pwm); }`,
  stop:  `void stopMotors(){ analogWrite(ENA,0); analogWrite(ENB,0); }`,
  led:   `void setLed(String c){ digitalWrite(LED_R, c=="red"||c=="white"); digitalWrite(LED_G, c=="green"||c=="white"); digitalWrite(LED_B, c=="blue"||c=="white"); }`,
  brightness: `float readBrightness(){ return analogRead(LDR_PIN) / 1023.0; }`,
  distance_ahead: `float readDistance(){ digitalWrite(TRIG_PIN,LOW); delayMicroseconds(2); digitalWrite(TRIG_PIN,HIGH); delayMicroseconds(10); digitalWrite(TRIG_PIN,LOW); long us=pulseIn(ECHO_PIN,HIGH); float cm=us/58.0; return min(cm/200.0, 1.0); }`,
};

const PY_HELPERS = {
  brightness: `def read_brightness():\n    return ldr.read() / 4095`,
  distance_ahead: `def read_distance():\n    return min(sonar.distance_cm() / 200, 1.0)`,
  beep: `def beep(freq):\n    buzz.freq(freq); buzz.duty(512); sleep_ms(150); buzz.duty(0)`,
  led: `def set_led(c):\n    r.value(c in ("red","white")); g.value(c in ("green","white")); b.value(c in ("blue","white"))`,
};

// ── Arduino C++ ──────────────────────────────────────────────────────────────

export function toArduino(program) {
  const used = program.usedPrimitives();
  const L = [];

  L.push(`// ─────────────────────────────────────────────`);
  L.push(`// Generated by Scrapcraft Maker Lab`);
  L.push(`// Brain: "${program.name}"  ·  Target: ${BRAINS[program.brain]?.chip ?? 'Arduino'}`);
  L.push(`// These are your tiles, as real firmware. Flash it to a robot.`);
  L.push(`// ─────────────────────────────────────────────`);
  L.push('');
  L.push('#define FORWARD 1');
  L.push('#define BACKWARD 0');
  L.push('#define RIGHT 1');
  L.push('#define LEFT 0');

  // Pin declarations from the hardware mappings of used primitives.
  const pins = collectPins([...used.actuators, ...used.sensors]);
  for (const p of pins) L.push(p);
  L.push('');

  // Helper fns.
  const helpers = new Set();
  for (const id of used.actuators) if (ARDUINO_HELPERS[id]) helpers.add(ARDUINO_HELPERS[id]);
  for (const id of used.sensors)   if (ARDUINO_HELPERS[id]) helpers.add(ARDUINO_HELPERS[id]);
  for (const h of helpers) L.push(h);
  if (helpers.size) L.push('');

  // setup()
  L.push('void setup() {');
  for (const id of [...used.actuators, ...used.sensors]) {
    const def = getActuator(id) ?? getSensor(id);
    const line = def?.hw?.setup?.arduino;
    if (line) L.push('  ' + line);
  }
  L.push('}');
  L.push('');

  // loop()
  const { loopBody, setupExtra } = splitRoots(program.nodes);
  L.push('void loop() {');
  emitArduino(loopBody, L, 1);
  L.push('}');

  return L.join('\n');
}

function emitArduino(nodes, L, depth) {
  const pad = '  '.repeat(depth);
  for (const node of nodes) {
    switch (node.type) {
      case 'action': {
        const def = getActuator(node.prim);
        L.push(pad + (def?.firmware?.arduino?.(node.params) ?? `/* ${node.prim} */`));
        break;
      }
      case 'wait':
        L.push(pad + `delay(${Math.round(node.seconds * 1000)});`);
        break;
      case 'if':
        L.push(pad + `if (${condArduino(node.cond)}) {`);
        emitArduino(node.body, L, depth + 1);
        L.push(pad + '}');
        break;
      case 'if_else':
        L.push(pad + `if (${condArduino(node.cond)}) {`);
        emitArduino(node.body, L, depth + 1);
        L.push(pad + '} else {');
        emitArduino(node.elseBody, L, depth + 1);
        L.push(pad + '}');
        break;
      case 'repeat': {
        const v = `i${depth}`;
        L.push(pad + `for (int ${v}=0; ${v}<${node.count}; ${v}++) {`);
        emitArduino(node.body, L, depth + 1);
        L.push(pad + '}');
        break;
      }
      case 'forever':
        L.push(pad + 'while (true) {');
        emitArduino(node.body, L, depth + 1);
        L.push(pad + '}');
        break;
      case 'macro':
        emitArduino(expandMacro(node) ?? [], L, depth);
        break;
    }
  }
}

function condArduino(cond) {
  if (!cond?.sensor) return 'false';
  const def = getSensor(cond.sensor);
  const expr = def?.firmware?.arduino?.() ?? 'false';
  let out;
  if (cond.cmp === 'is') out = cond.value ? `${expr}` : `!(${expr})`;
  else out = `${expr} ${cmpSym(cond.cmp)} ${Number(cond.value) || 0}`;
  return cond.not ? `!(${out})` : out;
}

// ── MicroPython ──────────────────────────────────────────────────────────────

export function toMicroPython(program) {
  const used = program.usedPrimitives();
  const L = [];
  L.push(`# Generated by Scrapcraft Maker Lab`);
  L.push(`# Brain: "${program.name}"  ·  Target: ${BRAINS[program.brain]?.chip ?? 'ESP32'}`);
  L.push('from machine import Pin, ADC, PWM');
  L.push('from time import sleep_ms, sleep');
  L.push('');
  // setup
  for (const id of [...used.actuators, ...used.sensors]) {
    const def = getActuator(id) ?? getSensor(id);
    const line = def?.hw?.setup?.micropython;
    if (line) L.push(line);
  }
  L.push('');
  const helpers = new Set();
  for (const id of [...used.actuators, ...used.sensors]) if (PY_HELPERS[id]) helpers.add(PY_HELPERS[id]);
  for (const h of helpers) { L.push(h); L.push(''); }

  const { loopBody } = splitRoots(program.nodes);
  L.push('while True:');
  emitPython(loopBody, L, 1);
  return L.join('\n');
}

function emitPython(nodes, L, depth) {
  const pad = '    '.repeat(depth);
  if (!nodes.length) { L.push(pad + 'pass'); return; }
  for (const node of nodes) {
    switch (node.type) {
      case 'action': {
        const def = getActuator(node.prim);
        L.push(pad + (def?.firmware?.micropython?.(node.params) ?? `# ${node.prim}`));
        break;
      }
      case 'wait':
        L.push(pad + `sleep(${node.seconds.toFixed(2)})`);
        break;
      case 'if':
        L.push(pad + `if ${condPython(node.cond)}:`);
        emitPython(node.body, L, depth + 1);
        break;
      case 'if_else':
        L.push(pad + `if ${condPython(node.cond)}:`);
        emitPython(node.body, L, depth + 1);
        L.push(pad + 'else:');
        emitPython(node.elseBody, L, depth + 1);
        break;
      case 'repeat':
        L.push(pad + `for _ in range(${node.count}):`);
        emitPython(node.body, L, depth + 1);
        break;
      case 'forever':
        L.push(pad + 'while True:');
        emitPython(node.body, L, depth + 1);
        break;
      case 'macro':
        emitPython(expandMacro(node) ?? [], L, depth);
        break;
    }
  }
}

function condPython(cond) {
  if (!cond?.sensor) return 'False';
  const def = getSensor(cond.sensor);
  const expr = def?.firmware?.micropython?.() ?? 'False';
  let out;
  if (cond.cmp === 'is') out = cond.value ? `${expr}` : `not (${expr})`;
  else out = `${expr} ${cmpSym(cond.cmp)} ${Number(cond.value) || 0}`;
  return cond.not ? `not (${out})` : out;
}

// ── shared helpers ───────────────────────────────────────────────────────────

function cmpSym(cmp) {
  return { gt: '>', lt: '<', gte: '>=', lte: '<=', eq: '==', neq: '!=', is: '==' }[cmp] ?? '>';
}

/** If the program is a single top-level forever, unwrap its body into loop(). */
function splitRoots(nodes) {
  if (nodes.length === 1 && nodes[0].type === 'forever') {
    return { loopBody: nodes[0].body, setupExtra: [] };
  }
  return { loopBody: nodes, setupExtra: [] };
}

/** Build pin #define lines from hw mappings (best-effort, de-duplicated). */
function collectPins(ids) {
  const defines = new Map();
  const add = (name, num) => { if (!defines.has(name)) defines.set(name, num); };
  for (const id of ids) {
    const def = getActuator(id) ?? getSensor(id);
    if (!def?.hw) continue;
    // Parse "NAME=NN" fragments out of pin / pins fields.
    const frags = [];
    if (def.hw.pin) frags.push(...String(def.hw.pin).split(','));
    if (def.hw.pins) for (const p of def.hw.pins) frags.push(...String(p).split(','));
    for (const f of frags) {
      const m = f.trim().match(/([A-Za-z0-9_]+)\s*=\s*(\d+)/);
      if (m) add(m[1], m[2]);
    }
    // Named conventional pins for the common primitives.
    if (id === 'brightness' || id === 'is_dark') add('LDR_PIN', 'A0');
    if (id === 'distance_ahead' || id === 'bumped') { add('TRIG_PIN', '5'); add('ECHO_PIN', '18'); }
    if (id === 'bumped') add('BUMP_PIN', '4');
    if (id === 'beep') add('BUZZ_PIN', '13');
    if (id === 'led') { add('LED_R', '14'); add('LED_G', '12'); add('LED_B', '33'); }
    if (id === 'drive' || id === 'turn' || id === 'stop') { add('IN1', '25'); add('IN2', '26'); add('ENA', '27'); add('ENB', '14'); }
    if (id === 'player_near') add('PIR_PIN', '19');
  }
  return [...defines.entries()].map(([n, v]) => `#define ${n} ${v}`);
}
