// ─────────────────────────────────────────────
// Generated by Scrapcraft Maker Lab
// Brain: "SENTRY chip breadboard"  ·  Target: ESP32
// These are your tiles, as real firmware. Flash it to a robot.
// ─────────────────────────────────────────────

#define FORWARD 1
#define BACKWARD 0
#define RIGHT 1
#define LEFT 0
#define TRIG 5
#define ECHO 18
#define TRIG_PIN 5
#define ECHO_PIN 18
#define ENA 27
#define ENB 14

bool sentryTripped=false; void sentryWatch(int tripPct,int clearPct){ digitalWrite(TRIG_PIN,LOW); delayMicroseconds(2); digitalWrite(TRIG_PIN,HIGH); delayMicroseconds(10); digitalWrite(TRIG_PIN,LOW); float d=min(pulseIn(ECHO_PIN,HIGH)/58.0/200.0,1.0); if(!sentryTripped&&d*100<tripPct){ sentryTripped=true; analogWrite(ENA,0); analogWrite(ENB,0); } else if(sentryTripped&&d*100>clearPct){ sentryTripped=false; } }

void setup() {
  pinMode(TRIG_PIN, OUTPUT); pinMode(ECHO_PIN, INPUT);
}

void loop() {
  sentryWatch(25, 40);
  delay(1000);
}
