// ─────────────────────────────────────────────
// Generated by Scrapcraft Maker Lab
// Brain: "WITNESS chip breadboard"  ·  Target: Arduino Uno (ATmega328P)
// These are your tiles, as real firmware. Flash it to a robot.
// ─────────────────────────────────────────────

#define FORWARD 1
#define BACKWARD 0
#define RIGHT 1
#define LEFT 0
#include <EEPROM.h>


void witnessTick(int addr){ byte c=EEPROM.read(addr); if(c<255) c++; EEPROM.update(addr,c); }

void setup() {
}

void loop() {
  witnessTick(0);
  delay(1000);
}
