// ─────────────────────────────────────────────
// Generated by Scrapcraft Maker Lab
// Brain: "RUMOR chip breadboard"  ·  Target: ESP32
// These are your tiles, as real firmware. Flash it to a robot.
// ─────────────────────────────────────────────

#define FORWARD 1
#define BACKWARD 0
#define RIGHT 1
#define LEFT 0
#define TX 17
#define RX 16

byte rumorIn=0; void rumorShare(byte f){ Serial1.write(f); if(Serial1.available()) rumorIn=Serial1.read(); }

void setup() {
  Serial1.begin(9600, SERIAL_8N1, 16, 17);
}

void loop() {
  rumorShare(1);
  delay(1000);
}
