export const PROVIDERS = [
  {
    id: 'anthropic',
    name: 'Anthropic Claude',
    icon: '🤖',
    models: ['claude-sonnet-4-20250514', 'claude-haiku-3-5', 'claude-opus-4'],
    defaultModel: 'claude-sonnet-4-20250514',
    requiresKey: true,
    keyName: 'ANTHROPIC_KEY',
    description: 'Best for Earl dialogue, Spark program generation, Codex explanations',
    tier: 'premium',
  },
  {
    id: 'openai',
    name: 'OpenAI GPT',
    icon: '⚡',
    models: ['gpt-4o', 'gpt-4o-mini'],
    defaultModel: 'gpt-4o-mini',
    requiresKey: true,
    keyName: 'OPENAI_KEY',
    description: 'Fast generation, good for Spark robot programs',
    tier: 'premium',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    icon: '🧠',
    models: ['deepseek-chat'],
    defaultModel: 'deepseek-chat',
    requiresKey: true,
    keyName: 'DEEPSEEK_KEY',
    description: 'Open source reasoning model — great value',
    tier: 'budget',
  },
  {
    id: 'z.ai',
    name: 'Z.AI',
    icon: '⚡',
    models: ['z-ai-chat'],
    defaultModel: 'z-ai-chat',
    requiresKey: true,
    keyName: 'ZAI_KEY',
    description: 'Fast inference provider',
    tier: 'budget',
  },
  {
    id: 'deepinfra',
    name: 'DeepInfra',
    icon: '☁️',
    models: ['mistralai/Mixtral-8x22B-Instruct-v0.1', 'meta-llama/Llama-3.3-70B-Instruct'],
    defaultModel: 'mistralai/Mixtral-8x22B-Instruct-v0.1',
    requiresKey: true,
    keyName: 'DEEPINFRA_KEY',
    description: 'Serverless GPU inference — open models',
    tier: 'budget',
  },
  {
    id: 'together',
    name: 'Together AI',
    icon: '🔮',
    models: ['mistralai/Mixtral-8x22B-Instruct-v0.1', 'meta-llama/Llama-3.3-70B-Instruct'],
    defaultModel: 'mistralai/Mixtral-8x22B-Instruct-v0.1',
    requiresKey: true,
    keyName: 'TOGETHER_KEY',
    description: 'Open-source model playground',
    tier: 'budget',
  },
  {
    id: 'workers_ai',
    name: 'Workers AI (Cloudflare)',
    icon: '🌤️',
    models: ['@cf/meta/llama-3.1-8b-instruct', '@cf/mistral/mistral-7b-instruct-v0.1'],
    defaultModel: '@cf/meta/llama-3.1-8b-instruct',
    requiresKey: false,
    keyName: null,
    description: 'Free tier — runs on Cloudflare GPU. No API key needed.',
    tier: 'free',
  },
];
